-- Name: All object test
-- Description: Every ship, station, and object.
-- Type: Basic

-- Stations
SpaceStation():setTemplate("Small Station"):setFaction("Independent"):setCallSign("DS1"):setPosition(-20000, 0)
SpaceStation():setTemplate("Medium Station"):setFaction("Independent"):setCallSign("DS2"):setPosition(-17500, -2500)
SpaceStation():setTemplate("Large Station"):setFaction("Independent"):setCallSign("DS3"):setPosition(-15000, -5000)
SpaceStation():setTemplate("Huge Station"):setFaction("Independent"):setCallSign("DS4"):setPosition(-12500, -7500)

-- Functional objects
WarpJammer():setFaction("Independent"):setPosition(250, 0)
Mine():setPosition(2500, -2500)
SupplyDrop():setFaction("Independent"):setPosition(5000, -5000):setEnergy(500):setWeaponStorage("Homing", 4):setWeaponStorage("Nuke", 1):setWeaponStorage("Mine", 2):setWeaponStorage("EMP", 1)

-- Space phenomena
Asteroid():setPosition(7500, -7500)
BlackHole():setPosition(20000, -20000)
Nebula():setPosition(20000, 0)
WormHole():setPosition(20000, 20000):setTargetPosition(-20000, -20000)

-- Ships
CpuShip():setFaction("Independent"):setTemplate("Adder MK4"):setCallSign("Adder MK4"):setPosition(-20000, 20000):orderRoaming():setWeaponStorage("HVLI", 1)
CpuShip():setFaction("Human Navy"):setTemplate("Adder MK5"):setCallSign("Adder MK5"):setPosition(-17556, 17667):orderRoaming():setWeaponStorage("HVLI", 3)
CpuShip():setFaction("Kraylor"):setTemplate("Adder MK6"):setCallSign("Adder MK6"):setPosition(-15000, 15111):orderRoaming():setWeaponStorage("HVLI", 7)
CpuShip():setFaction("Arlenians"):setTemplate("Adv. Gunship"):setCallSign("Adv. Gunship"):setPosition(-12444, 12667):orderRoaming():setWeaponStorage("Homing", 2)
CpuShip():setFaction("Exuari"):setTemplate("Adv. Striker"):setCallSign("Adv. Striker"):setPosition(-9778, 10000):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Atlantis X23"):setCallSign("Atlantis X23"):setPosition(-7333, 7556):orderRoaming():setWeaponStorage("Homing", 0)
CpuShip():setFaction("Ktlitans"):setTemplate("Battlestation"):setCallSign("Battlestation"):setPosition(-4667, 5111):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Blockade Runner"):setCallSign("Blockade Runner"):setPosition(-12444, 20111):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Cruiser"):setCallSign("Cruiser"):setPosition(-10000, 17556):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Defense platform"):setCallSign("Defense platform"):setPosition(-7444, 15222):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Dreadnought"):setCallSign("Dreadnought"):setPosition(-4889, 12667):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Equipment Freighter 1"):setCallSign("Equipment Freighter 1"):setPosition(-2444, 10222):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Equipment Freighter 2"):setCallSign("Equipment Freighter 2"):setPosition(111, 7667):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Equipment Freighter 3"):setCallSign("Equipment Freighter 3"):setPosition(2556, 5222):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Equipment Freighter 4"):setCallSign("Equipment Freighter 4"):setPosition(5222, 2556):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Equipment Freighter 5"):setCallSign("Equipment Freighter 5"):setPosition(7778, 222):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Equipment Jump Freighter 3"):setCallSign("Equipment Jump Freighter 3"):setPosition(10111, -2444):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Equipment Jump Freighter 4"):setCallSign("Equipment Jump Freighter 4"):setPosition(12556, -4889):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Equipment Jump Freighter 5"):setCallSign("Equipment Jump Freighter 5"):setPosition(15333, -7556):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Fighter"):setCallSign("Fighter"):setPosition(17556, -9667):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Flavia"):setCallSign("Flavia"):setPosition(-4667, 20000):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Flavia Falcon"):setCallSign("Flavia Falcon"):setPosition(-2333, 17667):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Fuel Freighter 1"):setCallSign("UTI23"):setPosition(333, 15333):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Fuel Freighter 2"):setCallSign("VK24"):setPosition(2667, 12556):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Fuel Freighter 3"):setCallSign("S25"):setPosition(5111, 10222):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Fuel Freighter 4"):setCallSign("VS26"):setPosition(7778, 7667):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Fuel Freighter 5"):setCallSign("CV27"):setPosition(10111, 5222):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Fuel Jump Freighter 3"):setCallSign("S28"):setPosition(12556, 2667):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Fuel Jump Freighter 4"):setCallSign("NC29"):setPosition(15000, 111):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Fuel Jump Freighter 5"):setCallSign("BR30"):setPosition(17556, -2444):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Garbage Freighter 1"):setCallSign("SS31"):setPosition(20222, -4778):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Garbage Freighter 2"):setCallSign("VS32"):setPosition(22444, -7333):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Garbage Freighter 3"):setCallSign("S33"):setPosition(25111, -9778):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Garbage Freighter 4"):setCallSign("CV34"):setPosition(27556, -12333):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Garbage Freighter 5"):setCallSign("CSS35"):setPosition(30222, -14889):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Garbage Jump Freighter 3"):setCallSign("VK36"):setPosition(32778, -17222):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Garbage Jump Freighter 4"):setCallSign("CCN37"):setPosition(35222, -19667):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Garbage Jump Freighter 5"):setCallSign("SS38"):setPosition(37556, -22222):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Goods Freighter 1"):setCallSign("BR39"):setPosition(2667, 20111):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Goods Freighter 2"):setCallSign("BR40"):setPosition(5222, 17667):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Goods Freighter 3"):setCallSign("UTI41"):setPosition(7556, 15222):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Goods Freighter 4"):setCallSign("NC42"):setPosition(10222, 12556):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Goods Freighter 5"):setCallSign("VS43"):setPosition(12667, 10222):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Goods Jump Freighter 3"):setCallSign("UTI44"):setPosition(15111, 7667):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Goods Jump Freighter 4"):setCallSign("VS45"):setPosition(17667, 5111):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Goods Jump Freighter 5"):setCallSign("S46"):setPosition(20111, 2556):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Ktlitan Breaker"):setCallSign("VS47"):setPosition(22444, 111):orderRoaming():setWeaponStorage("HVLI", 4)
CpuShip():setFaction("Exuari"):setTemplate("Ktlitan Destroyer"):setCallSign("VK48"):setPosition(25111, -2222):orderRoaming():setWeaponStorage("Homing", 22)
CpuShip():setFaction("Ghosts"):setTemplate("Ktlitan Drone"):setCallSign("CCN49"):setPosition(27667, -4778):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Ktlitan Feeder"):setCallSign("NC50"):setPosition(30444, -7333):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Ktlitan Fighter"):setCallSign("CCN51"):setPosition(32667, -9889):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Ktlitan Queen"):setCallSign("SS52"):setPosition(35222, -12333):orderRoaming():setWeaponStorage("EMP", 3)
CpuShip():setFaction("Kraylor"):setTemplate("Ktlitan Scout"):setCallSign("S53"):setPosition(37556, -14778):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Ktlitan Worker"):setCallSign("CV54"):setPosition(40222, -17444):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("MT52 Hornet"):setCallSign("CCN55"):setPosition(42667, -19889):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("MU52 Hornet"):setCallSign("CV56"):setPosition(45111, -22333):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Missile Cruiser"):setCallSign("VS57"):setPosition(10000, 20111):orderRoaming():setWeaponStorage("Homing", 9)
CpuShip():setFaction("Independent"):setTemplate("Nirvana R5"):setCallSign("CV58"):setPosition(12667, 17556):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Nirvana R5A"):setCallSign("SS59"):setPosition(15111, 15111):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Odin"):setCallSign("CCN60"):setPosition(17556, 12667):orderRoaming():setWeaponStorage("Homing", 984)
CpuShip():setFaction("Arlenians"):setTemplate("Personnel Freighter 1"):setCallSign("VK61"):setPosition(20222, 10222):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Personnel Freighter 2"):setCallSign("S62"):setPosition(22667, 7667):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Personnel Freighter 3"):setCallSign("CCN63"):setPosition(25222, 5333):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Personnel Freighter 4"):setCallSign("CCN64"):setPosition(27556, 2667):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Personnel Freighter 5"):setCallSign("CSS65"):setPosition(30222, 222):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Personnel Jump Freighter 3"):setCallSign("CCN66"):setPosition(32667, -2222):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Personnel Jump Freighter 4"):setCallSign("VS67"):setPosition(35222, -4778):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Personnel Jump Freighter 5"):setCallSign("CCN68"):setPosition(37778, -7333):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Phobos M3"):setCallSign("CV69"):setPosition(40111, -9778):orderRoaming():setWeaponStorage("Homing", 4)
CpuShip():setFaction("Ghosts"):setTemplate("Phobos T3"):setCallSign("CCN70"):setPosition(42667, -12333):orderRoaming():setWeaponStorage("Homing", 4)
CpuShip():setFaction("Ktlitans"):setTemplate("Piranha F12"):setCallSign("CV71"):setPosition(45222, -14778):orderRoaming():setWeaponStorage("Homing", 4):setWeaponStorage("HVLI", 16)
CpuShip():setFaction("Independent"):setTemplate("Piranha F12.M"):setCallSign("CV72"):setPosition(47778, -17444):orderRoaming():setWeaponStorage("Nuke", 0):setWeaponStorage("HVLI", 6)
CpuShip():setFaction("Human Navy"):setTemplate("Piranha F8"):setCallSign("CCN73"):setPosition(50333, -19889):orderRoaming():setWeaponStorage("Homing", 4):setWeaponStorage("HVLI", 8)
CpuShip():setFaction("Kraylor"):setTemplate("Ranus U"):setCallSign("SS74"):setPosition(52556, -22333):orderRoaming():setWeaponStorage("Homing", 4):setWeaponStorage("Nuke", 1)
CpuShip():setFaction("Kraylor"):setTemplate("Jump Carrier"):setCallSign("CNN60"):setPosition(55000, -25000):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Stalker Q7"):setCallSign("VK75"):setPosition(22889, 15333):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Stalker R7"):setCallSign("S76"):setPosition(25111, 12778):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Starhammer II"):setCallSign("CV77"):setPosition(27778, 10222):orderRoaming():setWeaponStorage("Homing", 3):setWeaponStorage("EMP", 1)
CpuShip():setFaction("Ktlitans"):setTemplate("Strikeship"):setCallSign("SS78"):setPosition(30222, 7556):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Transport1x1"):setCallSign("CSS79"):setPosition(32371, 4820):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Transport1x2"):setCallSign("UTI80"):setPosition(34923, 2647):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport1x3"):setCallSign("VK81"):setPosition(37192, 189):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Transport1x4"):setCallSign("UTI82"):setPosition(39933, -1985):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Transport1x5"):setCallSign("CV83"):setPosition(42012, -4537):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Transport2x1"):setCallSign("BR84"):setPosition(44753, -7372):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Transport2x2"):setCallSign("UTI85"):setPosition(47494, -9641):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Transport2x3"):setCallSign("UTI86"):setPosition(49857, -11909):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Transport2x4"):setCallSign("CCN87"):setPosition(52503, -14839):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport2x5"):setCallSign("VS88"):setPosition(55339, -17864):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport3x1"):setCallSign("CSS89"):setPosition(57702, -19754):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Transport3x2"):setCallSign("CCN90"):setPosition(60254, -22117):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("Transport3x3"):setCallSign("CV91"):setPosition(27456, 17486):orderRoaming()
CpuShip():setFaction("Ghosts"):setTemplate("Transport3x4"):setCallSign("BR92"):setPosition(29725, 14650):orderRoaming()
CpuShip():setFaction("Ktlitans"):setTemplate("Transport3x5"):setCallSign("SS93"):setPosition(32277, 12665):orderRoaming()
CpuShip():setFaction("Independent"):setTemplate("Transport4x1"):setCallSign("CSS94"):setPosition(34734, 10113):orderRoaming()
CpuShip():setFaction("Human Navy"):setTemplate("Transport4x2"):setCallSign("UTI95"):setPosition(37475, 7561):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport4x3"):setCallSign("UTI96"):setPosition(39838, 31853):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport4x3"):setCallSign("SS97"):setPosition(39744, 31664):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport4x3"):setCallSign("CV98"):setPosition(39838, 5388):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport4x4"):setCallSign("NC99"):setPosition(42485, 2646):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport4x5"):setCallSign("SS100"):setPosition(45131, 95):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport5x1"):setCallSign("VK101"):setPosition(47683, -2363):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport5x2"):setCallSign("BR102"):setPosition(50235, -4915):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport5x3"):setCallSign("BR103"):setPosition(52503, -7467):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport5x4"):setCallSign("CCN104"):setPosition(55244, -10019):orderRoaming()
CpuShip():setFaction("Kraylor"):setTemplate("Transport5x5"):setCallSign("CCN105"):setPosition(57607, -12193):orderRoaming()
CpuShip():setFaction("Arlenians"):setTemplate("Tug"):setCallSign("CV106"):setPosition(60159, -14934):orderRoaming()
CpuShip():setFaction("Exuari"):setTemplate("WX-Lindworm"):setCallSign("NC107"):setPosition(62239, -17675):orderRoaming():setWeaponStorage("Homing", 0):setWeaponStorage("HVLI", 4)
CpuShip():setFaction("Ghosts"):setTemplate("Weapons platform"):setCallSign("UTI108"):setPosition(65263, -19943):orderRoaming()
